/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF, useScroll } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import React, { useEffect, useRef } from "react";
import * as THREE from "three";

export function Ring(props) {
    const { nodes, materials } = useGLTF("/models/Ring.glb");
    return (
        <group {...props} dispose={null}>
            <group scale={2.563}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle.geometry}
                    material={materials["Material.001"]}
                    scale={74.509}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Original.geometry}
                    material={materials["Material.002"]}
                    position={[0.005, 0.841, 0.101]}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={53.42}
                />
            </group>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell006_cell001_cell.geometry}
                material={materials["Material.002"]}
                position={[-0.567, 2.411, -0.606]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell006_cell001_cell001.geometry}
                material={materials["Material.002"]}
                position={[-0.56, 2.35, -0.586]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell006_cell001_cell002.geometry}
                material={materials["Material.002"]}
                position={[-0.525, 2.137, -0.477]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell006_cell001_cell003.geometry}
                material={materials["Material.002"]}
                position={[-0.573, 2.38, -0.563]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell006_cell001_cell004.geometry}
                material={materials["Material.002"]}
                position={[-0.451, 2.209, -0.502]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell006_cell001_cell005.geometry}
                material={materials["Material.002"]}
                position={[-0.431, 2.138, -0.501]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell006_cell001_cell006.geometry}
                material={materials["Material.002"]}
                position={[-0.546, 2.255, -0.504]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell006_cell001_cell007.geometry}
                material={materials["Material.002"]}
                position={[-0.51, 2.341, -0.58]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell006_cell002_cell.geometry}
                material={materials["Material.002"]}
                position={[-0.14, 2.272, -0.949]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell006_cell002_cell001.geometry}
                material={materials["Material.002"]}
                position={[-0.105, 2.295, -0.951]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell006_cell002_cell002.geometry}
                material={materials["Material.002"]}
                position={[-0.301, 2.232, -0.957]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell006_cell002_cell003.geometry}
                material={materials["Material.002"]}
                position={[-0.155, 2.207, -0.966]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell006_cell002_cell004.geometry}
                material={materials["Material.002"]}
                position={[-0.339, 2.168, -0.975]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell006_cell002_cell005.geometry}
                material={materials["Material.002"]}
                position={[-0.412, 2.186, -0.987]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell006_cell002_cell006.geometry}
                material={materials["Material.002"]}
                position={[-0.17, 2.313, -0.934]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell006_cell002_cell007.geometry}
                material={materials["Material.002"]}
                position={[-0.19, 2.155, -0.978]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell006_cell003.geometry}
                material={materials["Material.002"]}
                position={[-0.254, 2.15, -0.82]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell006_cell004_cell.geometry}
                material={materials["Material.002"]}
                position={[-0.34, 2.295, -0.723]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell006_cell004_cell002.geometry}
                material={materials["Material.002"]}
                position={[-0.303, 2.08, -0.616]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell006_cell004_cell003.geometry}
                material={materials["Material.002"]}
                position={[-0.291, 2.046, -0.651]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell006_cell004_cell004.geometry}
                material={materials["Material.002"]}
                position={[-0.264, 2.002, -0.604]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell006_cell004_cell006.geometry}
                material={materials["Material.002"]}
                position={[-0.347, 2.358, -0.791]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell006_cell004_cell007.geometry}
                material={materials["Material.002"]}
                position={[-0.326, 2.206, -0.658]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell006_cell005_cell.geometry}
                material={materials["Material.002"]}
                position={[-0.238, 1.959, -0.716]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell006_cell005_cell001.geometry}
                material={materials["Material.002"]}
                position={[-0.333, 1.957, -0.795]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell006_cell005_cell002.geometry}
                material={materials["Material.002"]}
                position={[-0.279, 1.899, -0.705]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell006_cell005_cell003.geometry}
                material={materials["Material.002"]}
                position={[-0.311, 1.952, -0.734]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell006_cell005_cell004.geometry}
                material={materials["Material.002"]}
                position={[-0.291, 1.999, -0.669]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell006_cell005_cell005.geometry}
                material={materials["Material.002"]}
                position={[-0.364, 1.879, -0.681]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell006_cell005_cell006.geometry}
                material={materials["Material.002"]}
                position={[-0.345, 1.899, -0.663]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell006_cell005_cell007.geometry}
                material={materials["Material.002"]}
                position={[-0.3, 1.955, -0.625]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell006_cell006_cell.geometry}
                material={materials["Material.002"]}
                position={[-0.426, 2.136, -0.829]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell006_cell006_cell001.geometry}
                material={materials["Material.002"]}
                position={[-0.486, 2.064, -0.581]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell006_cell006_cell002.geometry}
                material={materials["Material.002"]}
                position={[-0.379, 2.003, -0.69]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell006_cell006_cell003.geometry}
                material={materials["Material.002"]}
                position={[-0.43, 1.925, -0.676]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell006_cell006_cell004.geometry}
                material={materials["Material.002"]}
                position={[-0.534, 2.128, -0.774]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell006_cell006_cell005.geometry}
                material={materials["Material.002"]}
                position={[-0.477, 2.297, -0.638]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell006_cell006_cell006.geometry}
                material={materials["Material.002"]}
                position={[-0.544, 1.939, -0.615]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell006_cell006_cell007.geometry}
                material={materials["Material.002"]}
                position={[-0.414, 2.157, -0.623]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell006_cell007_cell.geometry}
                material={materials["Material.002"]}
                position={[-0.695, 2.251, -0.701]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell006_cell007_cell001.geometry}
                material={materials["Material.002"]}
                position={[-0.696, 2.138, -0.633]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell006_cell007_cell002.geometry}
                material={materials["Material.002"]}
                position={[-0.637, 2.264, -0.594]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell006_cell007_cell004.geometry}
                material={materials["Material.002"]}
                position={[-0.705, 2.033, -0.538]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell006_cell007_cell005.geometry}
                material={materials["Material.002"]}
                position={[-0.636, 2.112, -0.505]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell006_cell007_cell006.geometry}
                material={materials["Material.002"]}
                position={[-0.61, 2.395, -0.613]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell006_cell007_cell007.geometry}
                material={materials["Material.002"]}
                position={[-0.643, 1.973, -0.533]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell006_cell_cell.geometry}
                material={materials["Material.002"]}
                position={[-0.255, 2.027, -0.681]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell006_cell_cell001.geometry}
                material={materials["Material.002"]}
                position={[-0.233, 1.995, -0.706]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell006_cell_cell002.geometry}
                material={materials["Material.002"]}
                position={[-0.233, 2.034, -0.673]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell006_cell_cell003.geometry}
                material={materials["Material.002"]}
                position={[-0.224, 2.058, -0.664]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell006_cell_cell004.geometry}
                material={materials["Material.002"]}
                position={[-0.227, 2.001, -0.694]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell006_cell_cell005_cell.geometry}
                material={materials["Material.002"]}
                position={[-0.243, 2.014, -0.688]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell006_cell_cell005_cell001.geometry}
                material={materials["Material.002"]}
                position={[-0.239, 2.026, -0.654]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell006_cell_cell005_cell002.geometry}
                material={materials["Material.002"]}
                position={[-0.251, 2.026, -0.667]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell006_cell_cell005_cell003.geometry}
                material={materials["Material.002"]}
                position={[-0.235, 2.012, -0.68]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell006_cell_cell005_cell004.geometry}
                material={materials["Material.002"]}
                position={[-0.244, 2.004, -0.698]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell006_cell_cell005_cell005.geometry}
                material={materials["Material.002"]}
                position={[-0.232, 2.007, -0.697]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell006_cell_cell005_cell006.geometry}
                material={materials["Material.002"]}
                position={[-0.238, 2.021, -0.667]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell006_cell_cell005_cell007.geometry}
                material={materials["Material.002"]}
                position={[-0.236, 2.002, -0.694]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell007_cell.geometry}
                material={materials["Material.002"]}
                position={[0.244, 1.73, -0.441]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell007_cell001.geometry}
                material={materials["Material.002"]}
                position={[-0.239, 1.72, -0.41]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell007_cell002.geometry}
                material={materials["Material.002"]}
                position={[-0.138, 1.828, -0.558]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell007_cell003.geometry}
                material={materials["Material.002"]}
                position={[0.189, 1.747, -0.272]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell007_cell004.geometry}
                material={materials["Material.002"]}
                position={[-0.014, 1.752, -0.438]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell007_cell005.geometry}
                material={materials["Material.002"]}
                position={[0.302, 1.78, -0.28]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell007_cell006.geometry}
                material={materials["Material.002"]}
                position={[-0.266, 1.822, -0.579]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell010.geometry}
                material={materials["Material.002"]}
                position={[1.235, 2.154, -0.151]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell016_cell.geometry}
                material={materials["Material.002"]}
                position={[-0.569, 2.087, 1.241]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell016_cell001.geometry}
                material={materials["Material.002"]}
                position={[-0.499, 2.011, 1.103]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell016_cell002.geometry}
                material={materials["Material.002"]}
                position={[-0.405, 1.912, 1.214]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell016_cell003.geometry}
                material={materials["Material.002"]}
                position={[-0.359, 1.909, 1.175]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell016_cell004.geometry}
                material={materials["Material.002"]}
                position={[-0.368, 2.08, 1.341]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell016_cell005.geometry}
                material={materials["Material.002"]}
                position={[-0.49, 2.204, 1.195]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell016_cell006.geometry}
                material={materials["Material.002"]}
                position={[-0.424, 2.023, 1.202]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell016_cell007.geometry}
                material={materials["Material.002"]}
                position={[-0.665, 2.258, 1.21]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell018_cell.geometry}
                material={materials["Material.002"]}
                position={[-0.98, 2.435, 0.528]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell018_cell001.geometry}
                material={materials["Material.002"]}
                position={[-1.119, 2.178, 0.755]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell018_cell002.geometry}
                material={materials["Material.002"]}
                position={[-1.121, 2.109, 0.696]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell018_cell004.geometry}
                material={materials["Material.002"]}
                position={[-1.106, 2.268, 0.592]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell018_cell005.geometry}
                material={materials["Material.002"]}
                position={[-1.16, 2.094, 0.656]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell018_cell006.geometry}
                material={materials["Material.002"]}
                position={[-1.171, 2.176, 0.754]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell018_cell007.geometry}
                material={materials["Material.002"]}
                position={[-1.04, 2.409, 0.484]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell019.geometry}
                material={materials["Material.002"]}
                position={[0.243, 2.147, -0.572]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell020_cell.geometry}
                material={materials["Material.002"]}
                position={[0.113, 2.304, 1.339]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell020_cell001.geometry}
                material={materials["Material.002"]}
                position={[-0.201, 2.289, 1.306]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell020_cell002.geometry}
                material={materials["Material.002"]}
                position={[-0.093, 2.376, 1.047]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell020_cell003.geometry}
                material={materials["Material.002"]}
                position={[0.152, 2.17, 1.137]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell020_cell004.geometry}
                material={materials["Material.002"]}
                position={[-0.344, 2.365, 1.193]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell020_cell005.geometry}
                material={materials["Material.002"]}
                position={[-0.234, 2.087, 1.07]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell020_cell006.geometry}
                material={materials["Material.002"]}
                position={[-0.093, 2.054, 1.234]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell020_cell007.geometry}
                material={materials["Material.002"]}
                position={[-0.117, 2.142, 1.448]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell024_cell.geometry}
                material={materials["Material.002"]}
                position={[0.713, 2.196, 1.253]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell024_cell001.geometry}
                material={materials["Material.002"]}
                position={[0.629, 2.085, 1.19]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell024_cell002.geometry}
                material={materials["Material.002"]}
                position={[0.277, 2.198, 1.456]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell024_cell003.geometry}
                material={materials["Material.002"]}
                position={[0.378, 2.286, 1.221]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell024_cell004.geometry}
                material={materials["Material.002"]}
                position={[0.398, 2.272, 1.308]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell024_cell005.geometry}
                material={materials["Material.002"]}
                position={[0.613, 2.302, 1.208]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell024_cell006.geometry}
                material={materials["Material.002"]}
                position={[0.462, 2.135, 1.173]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell024_cell007.geometry}
                material={materials["Material.002"]}
                position={[0.457, 2.137, 1.365]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell032_cell001.geometry}
                material={materials["Material.002"]}
                position={[1.132, 2.378, 0.242]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell032_cell002.geometry}
                material={materials["Material.002"]}
                position={[1.099, 2.382, 0.429]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell032_cell003.geometry}
                material={materials["Material.002"]}
                position={[1.138, 2.377, 0.386]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell032_cell004.geometry}
                material={materials["Material.002"]}
                position={[1.069, 2.385, 0.32]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell032_cell005.geometry}
                material={materials["Material.002"]}
                position={[1.072, 2.437, 0.371]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell032_cell006.geometry}
                material={materials["Material.002"]}
                position={[1.214, 2.285, 0.031]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell032_cell007.geometry}
                material={materials["Material.002"]}
                position={[1.034, 2.468, 0.285]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell033.geometry}
                material={materials["Material.002"]}
                position={[0.077, 1.905, 0.951]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell034.geometry}
                material={materials["Material.002"]}
                position={[0.263, 2.428, 0.891]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell035.geometry}
                material={materials["Material.002"]}
                position={[0.714, 2.261, -0.352]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell036_cell.geometry}
                material={materials["Material.002"]}
                position={[0.7, 2.346, 0.957]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell036_cell001.geometry}
                material={materials["Material.002"]}
                position={[0.859, 2.074, 0.883]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell036_cell002.geometry}
                material={materials["Material.002"]}
                position={[1.047, 2.319, 0.774]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell036_cell003.geometry}
                material={materials["Material.002"]}
                position={[1.023, 2.204, 0.919]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell036_cell004.geometry}
                material={materials["Material.002"]}
                position={[0.635, 2.28, 1.063]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell036_cell005.geometry}
                material={materials["Material.002"]}
                position={[0.849, 2.3, 1.023]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell036_cell006.geometry}
                material={materials["Material.002"]}
                position={[0.863, 2.215, 0.822]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell036_cell007.geometry}
                material={materials["Material.002"]}
                position={[0.747, 2.137, 0.979]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell037_cell.geometry}
                material={materials["Material.002"]}
                position={[-0.543, 2.46, -0.47]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell037_cell001.geometry}
                material={materials["Material.002"]}
                position={[-0.056, 2.367, -0.738]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell037_cell002.geometry}
                material={materials["Material.002"]}
                position={[0.089, 2.525, -0.486]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell037_cell003.geometry}
                material={materials["Material.002"]}
                position={[0.244, 2.522, -0.613]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell037_cell004.geometry}
                material={materials["Material.002"]}
                position={[-0.318, 2.458, -0.426]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell037_cell005.geometry}
                material={materials["Material.002"]}
                position={[-0.089, 2.272, -0.456]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell037_cell006.geometry}
                material={materials["Material.002"]}
                position={[-0.361, 2.244, -0.495]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell037_cell007.geometry}
                material={materials["Material.002"]}
                position={[-0.368, 2.444, -0.622]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell038_cell.geometry}
                material={materials["Material.002"]}
                position={[0.586, 1.772, 0.37]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell038_cell001.geometry}
                material={materials["Material.002"]}
                position={[0.53, 1.938, 0.784]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell038_cell002.geometry}
                material={materials["Material.002"]}
                position={[0.367, 1.751, 0.506]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell038_cell003.geometry}
                material={materials["Material.002"]}
                position={[0.489, 1.706, 0.7]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell038_cell004.geometry}
                material={materials["Material.002"]}
                position={[0.663, 1.818, 0.924]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell038_cell005.geometry}
                material={materials["Material.002"]}
                position={[0.737, 1.962, 0.716]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell038_cell006.geometry}
                material={materials["Material.002"]}
                position={[0.716, 1.736, 0.583]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell038_cell007.geometry}
                material={materials["Material.002"]}
                position={[0.653, 1.951, 1.032]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell039_cell.geometry}
                material={materials["Material.002"]}
                position={[0.501, 1.671, -0.099]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell039_cell001.geometry}
                material={materials["Material.002"]}
                position={[0.409, 1.756, -0.201]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell039_cell002.geometry}
                material={materials["Material.002"]}
                position={[0.601, 1.808, -0.124]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell039_cell003.geometry}
                material={materials["Material.002"]}
                position={[0.535, 1.705, -0.273]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell039_cell004.geometry}
                material={materials["Material.002"]}
                position={[0.753, 1.808, -0.212]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell039_cell005.geometry}
                material={materials["Material.002"]}
                position={[0.649, 1.717, 0.06]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell039_cell006.geometry}
                material={materials["Material.002"]}
                position={[0.317, 1.673, -0.155]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell039_cell007.geometry}
                material={materials["Material.002"]}
                position={[0.481, 1.828, -0.237]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell040_cell.geometry}
                material={materials["Material.002"]}
                position={[-0.563, 2.563, 0.164]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell040_cell001.geometry}
                material={materials["Material.002"]}
                position={[-0.836, 2.332, -0.148]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell040_cell002.geometry}
                material={materials["Material.002"]}
                position={[-0.616, 2.517, -0.122]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell040_cell003.geometry}
                material={materials["Material.002"]}
                position={[-0.749, 2.569, 0.232]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell040_cell004.geometry}
                material={materials["Material.002"]}
                position={[-0.664, 2.311, 0.041]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell040_cell005.geometry}
                material={materials["Material.002"]}
                position={[-0.485, 2.394, 0.067]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell040_cell006.geometry}
                material={materials["Material.002"]}
                position={[-0.838, 2.384, 0.054]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell040_cell007.geometry}
                material={materials["Material.002"]}
                position={[-0.573, 2.307, -0.226]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell041_cell.geometry}
                material={materials["Material.002"]}
                position={[-0.698, 2.392, -0.518]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell041_cell001.geometry}
                material={materials["Material.002"]}
                position={[-0.812, 2.217, -0.586]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell041_cell002.geometry}
                material={materials["Material.002"]}
                position={[-0.817, 2.119, -0.459]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell041_cell003.geometry}
                material={materials["Material.002"]}
                position={[-0.708, 2.409, -0.388]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell041_cell004.geometry}
                material={materials["Material.002"]}
                position={[-0.662, 2.247, -0.423]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell041_cell005.geometry}
                material={materials["Material.002"]}
                position={[-0.97, 2.226, -0.44]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell041_cell006.geometry}
                material={materials["Material.002"]}
                position={[-0.829, 2.283, -0.416]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell041_cell007.geometry}
                material={materials["Material.002"]}
                position={[-0.964, 2.185, -0.49]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell042_cell.geometry}
                material={materials["Material.002"]}
                position={[0.335, 2.227, -0.052]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell042_cell001.geometry}
                material={materials["Material.002"]}
                position={[0.627, 2.159, -0.062]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell042_cell002.geometry}
                material={materials["Material.002"]}
                position={[0.517, 2.508, -0.183]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell042_cell003.geometry}
                material={materials["Material.002"]}
                position={[0.385, 2.605, -0.336]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell042_cell004.geometry}
                material={materials["Material.002"]}
                position={[0.502, 2.32, 0.13]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell042_cell005.geometry}
                material={materials["Material.002"]}
                position={[0.915, 2.365, 0.083]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell042_cell006.geometry}
                material={materials["Material.002"]}
                position={[0.948, 2.275, -0.117]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell042_cell007.geometry}
                material={materials["Material.002"]}
                position={[1.216, 2.232, -0.067]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell043_cell.geometry}
                material={materials["Material.002"]}
                position={[1.063, 2.082, 0.796]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell043_cell001.geometry}
                material={materials["Material.002"]}
                position={[1.133, 2.179, 0.806]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell043_cell002.geometry}
                material={materials["Material.002"]}
                position={[1.194, 2.108, 0.713]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell043_cell003.geometry}
                material={materials["Material.002"]}
                position={[1.086, 2.092, 0.876]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell043_cell005.geometry}
                material={materials["Material.002"]}
                position={[1.202, 2.256, 0.517]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell043_cell006.geometry}
                material={materials["Material.002"]}
                position={[1.098, 2.332, 0.587]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell043_cell007.geometry}
                material={materials["Material.002"]}
                position={[1.128, 2.207, 0.666]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell044.geometry}
                material={materials["Material.002"]}
                position={[-0.951, 2.083, -0.198]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell045_cell.geometry}
                material={materials["Material.002"]}
                position={[1.053, 2.101, 0.582]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell045_cell001.geometry}
                material={materials["Material.002"]}
                position={[1.029, 2.017, -0.049]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell045_cell002.geometry}
                material={materials["Material.002"]}
                position={[0.764, 1.66, 0.228]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell045_cell003.geometry}
                material={materials["Material.002"]}
                position={[1.087, 2.253, 0.346]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell045_cell004.geometry}
                material={materials["Material.002"]}
                position={[1.11, 2.201, 0.094]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell045_cell005.geometry}
                material={materials["Material.002"]}
                position={[1.182, 2.095, -0.114]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell045_cell006.geometry}
                material={materials["Material.002"]}
                position={[1.177, 2.129, 0.03]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell045_cell007.geometry}
                material={materials["Material.002"]}
                position={[0.849, 1.934, 0.305]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell047_cell.geometry}
                material={materials["Material.002"]}
                position={[-0.876, 2.397, 0.229]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell047_cell001.geometry}
                material={materials["Material.002"]}
                position={[-0.997, 2.399, 0.449]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell047_cell002.geometry}
                material={materials["Material.002"]}
                position={[-1.031, 2.235, -0.002]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell047_cell003.geometry}
                material={materials["Material.002"]}
                position={[-0.862, 2.338, 0.373]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell047_cell004.geometry}
                material={materials["Material.002"]}
                position={[-0.977, 2.129, 0.459]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell047_cell005.geometry}
                material={materials["Material.002"]}
                position={[-0.836, 2.092, 0.162]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell047_cell006.geometry}
                material={materials["Material.002"]}
                position={[-1.055, 2.274, 0.235]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell047_cell007.geometry}
                material={materials["Material.002"]}
                position={[-0.954, 1.97, 0.163]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell048_cell.geometry}
                material={materials["Material.002"]}
                position={[-0.08, 1.795, 0.289]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell048_cell001.geometry}
                material={materials["Material.002"]}
                position={[0.313, 1.895, 0.069]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell048_cell002.geometry}
                material={materials["Material.002"]}
                position={[0.168, 1.854, 0.492]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell048_cell003.geometry}
                material={materials["Material.002"]}
                position={[0.081, 2.148, 0.289]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell048_cell004.geometry}
                material={materials["Material.002"]}
                position={[0.031, 2.12, 0.544]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell048_cell005.geometry}
                material={materials["Material.002"]}
                position={[0.378, 2.038, -0.088]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell048_cell006.geometry}
                material={materials["Material.002"]}
                position={[-0.262, 1.854, 0.417]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell049_cell001.geometry}
                material={materials["Material.002"]}
                position={[-0.538, 2.168, 0.345]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell049_cell002.geometry}
                material={materials["Material.002"]}
                position={[-0.432, 2.453, 0.364]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell049_cell003.geometry}
                material={materials["Material.002"]}
                position={[-0.729, 2.466, 0.528]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell049_cell004.geometry}
                material={materials["Material.002"]}
                position={[-0.912, 2.089, 0.633]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell049_cell005.geometry}
                material={materials["Material.002"]}
                position={[-0.32, 2.27, 0.722]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell049_cell006.geometry}
                material={materials["Material.002"]}
                position={[-0.225, 2.41, 0.573]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell049_cell007.geometry}
                material={materials["Material.002"]}
                position={[-0.665, 2.347, 0.958]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell050_cell.geometry}
                material={materials["Material.002"]}
                position={[-0.743, 1.813, 0.467]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell050_cell001.geometry}
                material={materials["Material.002"]}
                position={[-0.24, 1.676, 0.974]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell050_cell002.geometry}
                material={materials["Material.002"]}
                position={[-0.405, 1.915, 0.548]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell050_cell003.geometry}
                material={materials["Material.002"]}
                position={[-0.478, 1.728, 0.465]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell050_cell004.geometry}
                material={materials["Material.002"]}
                position={[-0.36, 1.825, 1.011]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell050_cell005.geometry}
                material={materials["Material.002"]}
                position={[-0.317, 1.707, 0.758]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell050_cell006.geometry}
                material={materials["Material.002"]}
                position={[-0.729, 1.914, 0.874]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell050_cell007.geometry}
                material={materials["Material.002"]}
                position={[-0.47, 1.88, 0.835]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell051_cell.geometry}
                material={materials["Material.002"]}
                position={[0.351, 2.569, -0.374]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell051_cell001.geometry}
                material={materials["Material.002"]}
                position={[0.344, 2.609, -0.38]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell051_cell003.geometry}
                material={materials["Material.002"]}
                position={[0.326, 2.526, -0.607]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell051_cell004.geometry}
                material={materials["Material.002"]}
                position={[0.384, 2.552, -0.538]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell051_cell005.geometry}
                material={materials["Material.002"]}
                position={[0.418, 2.627, -0.373]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell051_cell006.geometry}
                material={materials["Material.002"]}
                position={[0.362, 2.592, -0.435]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell051_cell007.geometry}
                material={materials["Material.002"]}
                position={[0.312, 2.576, -0.51]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell052_cell001.geometry}
                material={materials["Material.002"]}
                position={[-0.399, 2.567, 1.019]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell052_cell002.geometry}
                material={materials["Material.002"]}
                position={[-0.405, 2.603, 0.973]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell052_cell003.geometry}
                material={materials["Material.002"]}
                position={[-0.203, 2.563, 1.019]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell052_cell004.geometry}
                material={materials["Material.002"]}
                position={[-0.141, 2.58, 0.926]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell052_cell005.geometry}
                material={materials["Material.002"]}
                position={[-0.268, 2.569, 0.916]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell052_cell006.geometry}
                material={materials["Material.002"]}
                position={[-0.343, 2.598, 0.86]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell052_cell007.geometry}
                material={materials["Material.002"]}
                position={[-0.144, 2.568, 0.679]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell053_cell.geometry}
                material={materials["Material.002"]}
                position={[-0.102, 2.412, -0.046]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell053_cell001.geometry}
                material={materials["Material.002"]}
                position={[-0.072, 2.58, -0.274]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell053_cell002.geometry}
                material={materials["Material.002"]}
                position={[-0.246, 2.477, 0.329]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell053_cell003.geometry}
                material={materials["Material.002"]}
                position={[0.172, 2.419, 0.094]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell053_cell004.geometry}
                material={materials["Material.002"]}
                position={[0.215, 2.501, -0.273]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell053_cell005.geometry}
                material={materials["Material.002"]}
                position={[0.024, 2.453, 0.438]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell053_cell006.geometry}
                material={materials["Material.002"]}
                position={[-0.218, 2.613, -0.198]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell053_cell007.geometry}
                material={materials["Material.002"]}
                position={[-0.029, 2.458, 0.225]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell054_cell.geometry}
                material={materials["Material.002"]}
                position={[-0.595, 2.052, -0.208]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell054_cell001.geometry}
                material={materials["Material.002"]}
                position={[-0.361, 1.916, -0.481]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell054_cell002.geometry}
                material={materials["Material.002"]}
                position={[-0.456, 1.764, -0.172]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell054_cell003.geometry}
                material={materials["Material.002"]}
                position={[-0.356, 1.817, 0.205]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell054_cell004.geometry}
                material={materials["Material.002"]}
                position={[-0.124, 2.004, -0.304]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell054_cell005.geometry}
                material={materials["Material.002"]}
                position={[-0.153, 1.808, -0.099]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell054_cell006.geometry}
                material={materials["Material.002"]}
                position={[-0.591, 1.933, 0.14]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell054_cell007.geometry}
                material={materials["Material.002"]}
                position={[-0.218, 2.13, -0.036]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell056_cell.geometry}
                material={materials["Material.002"]}
                position={[0.815, 2.266, 0.596]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell056_cell001.geometry}
                material={materials["Material.002"]}
                position={[0.755, 2.43, 0.351]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell056_cell002.geometry}
                material={materials["Material.002"]}
                position={[0.661, 2.48, 0.785]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell056_cell003.geometry}
                material={materials["Material.002"]}
                position={[0.663, 2.543, 0.517]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell056_cell004.geometry}
                material={materials["Material.002"]}
                position={[0.509, 2.245, 0.624]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell056_cell006.geometry}
                material={materials["Material.002"]}
                position={[0.97, 2.396, 0.465]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell056_cell007.geometry}
                material={materials["Material.002"]}
                position={[0.439, 2.331, 0.45]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell057_cell.geometry}
                material={materials["Material.002"]}
                position={[-0.801, 1.777, 0.21]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell057_cell001.geometry}
                material={materials["Material.002"]}
                position={[-0.706, 1.704, 0.201]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell057_cell002.geometry}
                material={materials["Material.002"]}
                position={[-0.875, 1.812, 0.103]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell057_cell003.geometry}
                material={materials["Material.002"]}
                position={[-0.506, 1.621, -0.209]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell057_cell004.geometry}
                material={materials["Material.002"]}
                position={[-0.58, 1.656, -0.028]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell057_cell005.geometry}
                material={materials["Material.002"]}
                position={[-0.741, 1.728, 0.052]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell057_cell006.geometry}
                material={materials["Material.002"]}
                position={[-0.545, 1.635, -0.251]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Gem_cell057_cell007.geometry}
                material={materials["Material.002"]}
                position={[-0.587, 1.693, 0.212]}
            />
        </group>
    );
}

useGLTF.preload("/models/Ring.glb");